
monitor=,preferred,auto,auto

$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

$hypr = ~/.config/hypr
$shortcut = hyprCut.conf
$var = hyprVar.conf

#load other files
source = $hypr/$shortcut
source = $hypr/$var

env = XCURSOR_SIZE,8
env = HYPRCURSOR_SIZE,8

