

source = ~/.config/hypr/hyprDeco.conf
source = ~/.config/hypr/hyprCut.conf
source = ~/.config/hypr/hyprVar.conf
source = ~/.config/hypr/hyprExec.conf

monitor=...,preferred,auto,1
xwayland {
    force_zero_scaling = true
    use_nearest_neighbor = false
}   
